server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventariodb
    username: root
    password: tu_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: msvc-inventario

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
