server:
  port: 8008

spring:
  application:
    name: msvc-clienteweb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
