server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/agencia_eventos_db
    username: root
    password: tu_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

  application:
    name: msvc-clientes

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
