server:
  port: 8017

spring:
  application:
    name: msvc-employees

  datasource:
    url: jdbc:mysql://mysql:3306/agencia_eventos_db
    username: root
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
