server:
  port: 8761
  address: 0.0.0.0

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      uri: http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
