# Etapa 1: Construcción del JAR con Maven
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app

# Copiamos el proyecto
COPY . .

# Compilamos el JAR
RUN mvn clean package -DskipTests

# Etapa 2: Imagen final
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copiamos el JAR desde la etapa anterior
COPY --from=build /app/target/*.jar app.jar


EXPOSE 8080

# Comando de arranque
ENTRYPOINT ["java", "-jar", "app.jar"]
